# 站点名称
site_name: 'Hexo-NexT'
# 仓库链接
repo_url: https://github.com/ZJDoc/Hexo-NexT
# 作者
site_author: 'zhujian'
# 版权信息
copyright: '2021, zhujian'
# 源文件目录
docs_dir: 'docs'
# 生成静态文件目录
site_dir: 'site'
# 额外信息
extra:
    # 版本号
    version: 0.1.0
# 主题
theme: 
    # name: 'readthedocs'
    # name: 'mkdocs'
    name: 'material'
# markdown扩展
markdown_extensions:
  # mathjax
  - pymdownx.arithmatex:
      generic: true
    
# mathjax
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# 导航
nav:
    - Home: index.md
    - Hexo:
      - 引言: hexo/index.md
      - Get Started:
        - 初识Hexo: hexo/base/初识Hexo.md
        - Hexo安装: hexo/base/Hexo安装.md
        - 新建网站: hexo/base/新建网站.md
        - 文件添加: hexo/base/文件添加.md
        - 文件配置: hexo/base/文件配置.md
        - 本地服务器: hexo/base/本地服务器.md
      - Advanced:
        - Hexo命令: hexo/advanced/Hexo命令.md
        - 类别&标签: hexo/advanced/类别&标签.md
        - 永久链接: hexo/advanced/永久链接.md
        - 代码块设置: hexo/advanced/代码块设置.md
        - 资源文件: hexo/advanced/资源文件.md
        - 404页面: hexo/advanced/404页面.md
        - '[gulp]性能优化': hexo/advanced/gulp-性能优化.md