# 站点名称
site_name: 'Hexo-NexT'
# 仓库链接
repo_url: https://github.com/ZJDoc/Hexo-NexT
# 作者
site_author: 'zhujian'
# 版权信息
copyright: '2021, zhujian'
# 源文件目录
docs_dir: 'docs'
# 生成静态文件目录
site_dir: 'site'
# 额外信息
extra:
    # 版本号
    version: 0.1.0
# 主题
theme: 
    # name: 'readthedocs'
    # name: 'mkdocs'
    name: 'material'
# markdown扩展
markdown_extensions:
  # mathjax
  - pymdownx.arithmatex:
      generic: true
    
# mathjax
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# 导航
nav:
    - Home: index.md
    - Hexo:
      - 引言: hexo/index.md
      - Get Started:
        - 初识Hexo: hexo/base/初识Hexo.md
        - Hexo安装: hexo/base/Hexo安装.md
        - 新建网站: hexo/base/新建网站.md
        - 文件添加: hexo/base/文件添加.md
        - 文件配置: hexo/base/文件配置.md
        - 本地服务器: hexo/base/本地服务器.md
      - Advanced:
        - Hexo命令: hexo/advanced/Hexo命令.md
        - 类别&标签: hexo/advanced/类别&标签.md
        - 永久链接: hexo/advanced/永久链接.md
        - 代码块设置: hexo/advanced/代码块设置.md
        - 资源文件: hexo/advanced/资源文件.md
        - 404页面: hexo/advanced/404页面.md
        - '[gulp]性能优化': hexo/advanced/gulp-性能优化.md
    - NexT:
      - 引言: next/index.md
      - Base:
        - 版本管理: next/base/版本管理.md
        - 语言设置: next/base/语言设置.md
        - 布局设置: next/base/布局设置.md
        - 首页预览: next/base/首页预览.md
        - 菜单栏: next/base/菜单栏.md
        - 侧边栏: next/base/侧边栏.md
        - 代码块配置: next/base/代码块配置.md
        - Github图标: next/base/Github图标.md
        - 版权信息: next/base/版权信息.md
        - 打赏功能: next/base/打赏功能.md
        - 标签页设置: next/base/标签页设置.md
        - 标签云: next/base/标签云.md
      - Advanced:
        - 加载进度条: next/advanced/加载进度条.md
        - 配置MathJax: next/advanced/配置MathJax.md
        - 动态背景: next/advanced/动态背景.md
        - 搜索服务: next/advanced/搜索服务.md
        - 字数统计: next/advanced/字数统计.md
        - 字体设置: next/advanced/字体设置.md
        - RSS支持: next/advanced/RSS支持.md
        - 首页置顶: next/advanced/首页置顶.md
        - 图片显示: next/advanced/图片显示.md
        - 调整页面宽度: next/advanced/调整页面宽度.md
        - '[Gitalk]评论系统': next/advanced/gitalk-评论系统.md
        - '[不蒜子]文章阅读次数': next/advanced/不蒜子-文章阅读次数.md
        - '[百度统计]网站访问': next/advanced/百度统计-网站访问.md
        - '[Baidu][Google]站点地图': next/advanced/Baidu-Google-站点地图.md
    - Deploy: deploy.md